services:
  secta-crm:
    container_name: secta-crm
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./secta-crm:/secta-crm
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
